project:
  render: 
    - "*.qmd"
    - "!TP_MAF_exemple.qmd"
  type: website

website:
  title: "Statistique Spatiale"
  navbar:
    right:
      - href: index.qmd
        text: Home
    left:
      - icon: github
        href: https://github.com/MarieEtienne/statspat.git
        aria-label: GitHub
      - text: "References "
        menu: 
          - text: Cours        
            href: references_statspat.qmd
      - text: "Cours"
        menu: 
          - href: 01_intro.qmd
          - href: 02_geostat.qmd
          - href: 03_lattice.qmd
          - href: 04_inla.qmd

      - text: "TP"
        menu: 
          - href: 01_pluies.qmd
          - href: 01_tp_sf.qmd
          - href: tp_reseau.qmd
          - href: 02_tpintro_inla.qmd
          - href: 03_tp_inlaspatial.qmd
      - text: "Evaluation"
        menu: 
          - href: eval_spatial.qmd

          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

